// Auto-generated component type declarations — do not edit
// Generated by fluxion-core::ComponentRegistry

interface Camera {
  /** Fov */
  fov: number;
  /** Near */
  near: number;
  /** Far */
  far: number;
  /** Projection Mode */
  projection_mode: string;
  /** Ortho Size */
  ortho_size: number;
  /** Is Active */
  is_active: boolean;
  /** Render To Texture */
  render_to_texture: string | undefined;
}

interface Light {
  /** Light Type */
  light_type: string;
  /** Color */
  color: [number, number, number];
  /** Intensity */
  intensity: number;
  /** Range */
  range: number;
  /** Spot Angle */
  spot_angle: number;
  /** Spot Penumbra */
  spot_penumbra: number;
  /** Cast Shadow */
  cast_shadow: boolean;
  /** Shadow Map Size */
  shadow_map_size: number;
  /** Shadow Bias */
  shadow_bias: number;
}

interface MeshRenderer {
  /** Mesh Path */
  mesh_path: string | undefined;
  /** Material Path */
  material_path: string | undefined;
  /** Cast Shadow */
  cast_shadow: boolean;
  /** Receive Shadow */
  receive_shadow: boolean;
  /** Layer */
  layer: number;
}

interface ParticleEmitter {
  /** Max Particles */
  max_particles: number;
  /** Spawn Per Second */
  spawn_per_second: number;
  /** Lifetime */
  lifetime: number;
  /** Start Speed */
  start_speed: number;
  /** Gravity */
  gravity: [number, number, number];
  /** Color */
  color: [number, number, number, number];
  /** Size */
  size: number;
  /** Spread Degrees */
  spread_degrees: number;
}

interface RigidBody {
  /** Shape */
  shape: string;
  /** Body Type */
  body_type: string;
  /** Mass */
  mass: number;
  /** Linear Damping */
  linear_damping: number;
  /** Angular Damping */
  angular_damping: number;
  /** Gravity Scale */
  gravity_scale: number;
  /** Can Sleep */
  can_sleep: boolean;
  /** Restitution */
  restitution: number;
  /** Friction */
  friction: number;
}

interface Transform {
  /** Position */
  position: [number, number, number];
  /** Rotation */
  rotation: [number, number, number, number];
  /** Scale */
  scale: [number, number, number];
  /** World Position */
  readonly world_position: [number, number, number];
  /** World Rotation */
  readonly world_rotation: [number, number, number, number];
  /** World Scale */
  readonly world_scale: [number, number, number];
}

type ComponentName = "Camera" | "Light" | "MeshRenderer" | "ParticleEmitter" | "RigidBody" | "Transform";
